---
name: eShopOnWeb CI
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore
        run: dotnet restore eShopOnWeb.sln
      - name: Build
        run: dotnet build eShopOnWeb.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test eShopOnWeb.sln --no-build --verbosity normal
      - name: Publish
        run: dotnet publish src/Web/Web.csproj -c Release -o publishedapp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-site
          path: publishedapp
